FROM python:3.10

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1
ENV PORT=8000

WORKDIR /app

COPY ./compose/requirements.txt .

RUN apt-get update && apt-get install --no-install-recommends -y \
    build-essential && pip install -r requirements.txt

COPY . .

RUN mkdir -p /app/logs

EXPOSE $PORT

# RUN python manage.py migrate
# RUN python manage.py collectstatic --noinput
# COPY ./compose/start.sh start.sh
RUN sed -i 's/\r$//g' ./compose/start.sh && chmod +x ./compose/start.sh

# CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
CMD ["./compose/start.sh"]
