version: '3'
services:

  django:
    build:
      context: ..
      dockerfile: ./compose/dockerfile-old
    image: slb59/lettings
    container_name: lettings
    depends_on:
      - memcached
      - redis
    env_file:
      - ../.env
    ports:
      - 8000:8000
    command: /start

  memcached:
    image: memcached:latest
    container_name: memcached
  
  redis:
    image: redis:latest
    container_name: redis
