FROM python:3.10

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1
ENV PORT=8000

# ENV VIRTUAL_ENV=/opt/venv
# RUN python3 -m venv $VIRTUAL_ENV
# ENV PATH="$VIRTUAL_ENV/bin:$PATH"

WORKDIR /app

COPY ./requirements.txt .

RUN apt-get update && apt-get install --no-install-recommends -y \
    build-essential && pip install -r requirements.txt

COPY . .

RUN mkdir -p /app/logs

EXPOSE $PORT

RUN sed -i 's/\r$//g' ./compose/start.sh && chmod +x ./compose/start.sh

CMD ["./compose/start.sh"]
