FROM python:3.10

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

WORKDIR /app

COPY ./compose/requirements.txt .

RUN apt-get update && apt-get install --no-install-recommends -y \
    build-essential && pip install -r requirements.txt

COPY . .

RUN mkdir -p /app/logs

RUN python manage.py migrate
RUN python manage.py runserver 0.0.0.0:8000