version: '3'
services:

  django:
    build:
      context: ..
      dockerfile: ./compose/dockerfile
    image: slb59/lettings
    container_name: lettings
    depends_on:
      - database
      - memcached
      - redis
    env_file:
      - ../.env
    ports:
      - 8000:8000
    command: /start

  database:
    image: keinos/sqlite3:latest
    container_name: sqlite_base
    env_file:
      - ../.env
    volumes:
      - lettings_data:/data
  
  memcached:
    image: memcached:latest
    container_name: memcached
  
  redis:
    image: redis:latest
    container_name: redis


volumes:
  lettings_data: {}