FROM python:3.10
ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1
WORKDIR /app
COPY requirements.txt /app
RUN apt-get update && apt-get install --no-install-recommends -y \
    build-essential
RUN pip install -r requirements.txt