# Generated by Django 3.0 on 2023-10-11 13:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("oc_lettings_site", "0002_delete_address_letting"),
        ("profiles", "0002_data_from_oc_profile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
